### ISSUE TITLE
Example docs mangling url

### ISSUE THREAD

**Issue by CallumDowling** [petertrotman/actix-web-middleware-redirect-https#1]
Hi, not sure if I am using this incorrectly but when I use the function:    

``` .wrap(RedirectHTTPS::with_replacements(&[(":8080".to_owned(), ":8443".to_owned())]))```    

With 2 apps running on 8080 and 8443 respectively, when I type localhost:8080, I get redirected to a weird port (https://localhost44380/).    

When I use "8080" and "8443", it works.

actix-web 2.0    

actix-web-middleware-redirect-https 1.0.0

**Comment by petertrotman** [comment]
Hey, thanks for the issue - did you resolve this in the end or is it still a bug?

**Comment by CallumDowling** [comment]
Looks like I solved it with the following, though it has been a while
```
<my app>
})
.bind_openssl(ssl_address, builder).expect("Cannot bind to ssl port.")
    .run();
    let non_ssl_server = HttpServer::new(move || {
        App::new()
            .wrap(RedirectHTTPS::with_replacements(&[(env::var("NON_SSL_PORT").unwrap().to_owned(), env::var("SSL_PORT").unwrap().to_owned()), (env::var("SSL_PORT").unwrap().to_owned(), env::var("SSL_PORT").unwrap().to_owned())]))
    })
    .bind(non_ssl_address).expect("Cannot bind to non ssl port")
    .run();
    future::try_join(ssl_server, non_ssl_server).await?;
```
